version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: notebook
      POSTGRES_USER: notebook_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/notebook
      SPRING_DATASOURCE_USERNAME: notebook_user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db